# version is set in tools\appveyor.psm1 - Invoke-AppVeyorInstall

image: Visual Studio 2017

# cache version - netcoreapp.2.0.6-sdk.2.1.4
cache:
  - '%LocalAppData%\Microsoft\dotnet -> appveyor.yml'
  - '%HOMEDRIVE%%HOMEPATH%\.nuget\packages -> appveyor.yml'

nuget:
  project_feed: true

install:
  - git submodule update --init
  - ps: Import-Module .\tools\Appveyor.psm1
  - ps: Invoke-AppveyorInstall

build_script:
  - ps:  Import-Module .\tools\Appveyor.psm1; Invoke-AppveyorBuild

test_script:
  - pwsh:  Import-Module .\tools\Appveyor.psm1; Invoke-AppveyorTest

after_test:
  - pwsh:  Import-Module .\tools\Appveyor.psm1; Invoke-AppVeyorAfterTest

on_finish:
  - ps: Import-Module .\tools\Appveyor.psm1; Invoke-AppveyorFinish
